name: pytest
on: workflow_dispatch

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: clone reposity
        run: |
          git clone https://github.com/icechase/github-actions-python01
          cd github-actions-python01
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest



